README.md update for TypeScript
Updated to the proper import for TypeScript for this module format. Using "import * as asyncHandler ..."  will result in warning "Cannot Invoke an Expression whose Type Lacks a Call Signature"  and compile to TypeError: asyncHandler is not a function